---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: mongodb-port
    protocol: TCP
  selector:
    app: mongodb
  type: NodePort