# Kafka image without the service, so you can run ./bin/ stuff
# kubectl exec -ti testclient -- /bin/bash
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: kafka
  labels: 
    app: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo:latest
    command:
      - mongod
      - "--bind_ip"
      - "0.0.0.0"
    ports:
      - containerPort: 27017