# Kafka image without the service, so you can run ./bin/ stuff
# kubectl exec -ti testclient -- /bin/bash
apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer1
  namespace: kafka
spec:
  containers:
  - name: testcons
    image: kafka_consumer
    imagePullPolicy: IfNotPresent
    command:
      - python
      - app.py